[package]
name = "vector_example1"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
criterion = "0.5.1"
clap = { version = "4.5.21", features = ["derive"] }

[profile.release]
debug = "full"

[[bench]]
name = "my_benchmark"
harness = false

