[package]
name = "try_arrow"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "54.3.1"
arrow-cast = { version = "54.3.1", features = ["prettyprint"] }
memmap2 = "0.9.5"
bytes = "1.10.1"

[profile.dev]
debug = true
